apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-server-deployment
  labels:
    app: ftp-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ftp-server
  template:
    metadata:
      labels:
        app: ftp-server
    spec:
      containers:
        - name: ftp-server
          image: {{ .Values.image }}
          ports:
            - containerPort: 22
          args: ["admin:admin:1000::"]
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-server-service
  labels:
    app: ftp-server
spec:
  type: ClusterIP
  ports:
    - port: 6000
      targetPort: 22
      protocol: TCP
      name: ftp
  selector:
    app: ftp-server
